export const cardsData = [
  {
    id: 1,
    title: "Task 1",
    datetime: "24/1/2022 16:40hs",
    creator: "Julio Avantt",
    description: "Description 1",
    type: "new",
    priority: "high",
  },
  {
    id: 2,
    title: "Task 2",
    datetime: "24/1/2022 16:40hs",
    creator: "Julio Avantt",
    description: "Description 2",
    type: "new",
    priority: "high",
  },
  {
    id: 3,
    title: "Task 3",
    datetime: "24/1/2022 16:40hs",
    creator: "Julio Avantt",
    description: "Description 3",
    type: "new",
    priority: "high",
  },
  {
    id: 4,
    title: "Task 4",
    datetime: "24/1/2022 16:40hs",
    creator: "Julio Avantt",
    description: "Description 4",
    type: "new",
    priority: "high",
  },
  {
    id: 6,
    title: "Task 6",
    datetime: "24/1/2022 16:40hs",
    creator: "Julio Avantt",
    description: "Description 6",
    type: "new",
    priority: "high",
  },
];
